language: node_js
node_js:
  - "6"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm run build.prod

deploy:
  provider: surge
  project: ./dist/
  domain: whatissytems.surge.sh
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
